[package]
name = "rushterm"
version = "0.1.1"
edition = "2021"
description = "Create nested menus on the terminal, navigate with hotkeys. Data-driven. No function/macro complexity."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.22.1" }
